---

# This is the string configuration file for English.
en-GB:
  # Dummy Groove
  groove_name_dummy: Dummy
  groove_description_dummy: Utterly pointless
  
  
  # Actions
  trigger_action_name_modify_experience: "Unit: Modify Experience"
  trigger_action_description_modify_experience: "Modifies selected units' experience by adding to it, subtracting from it or setting it to a specific value."
  trigger_action_readable_modify_experience: "Modify experience of {0} at {1} for {2}: {3} {4}."
  
  trigger_action_name_modify_rank: "Unit: Modify Rank"
  trigger_action_description_modify_rank: "Modifies selected units' rank by adding to it, subtracting from it or setting it to a specific value."
  trigger_action_readable_modify_rank: "Modify rank of {0} at {1} for {2}: {3} {4}."
  
  trigger_action_name_update_leveling: "UI: Update Leveling UI"
  trigger_action_description_update_leveling: "Do not use. Technical action for save and load purposes."
  trigger_action_description_update_leveling: "Update leveling UI."
  
  # Conditions
  trigger_condition_name_experience: "Unit: Experience"
  trigger_condition_description_experience: "Triggers based on the experience of a certain unit."
  trigger_condition_readable_experience: "Does {0} have {1} {2} of {3} at {4} with {5} {6} experience?"
  
  trigger_condition_name_rank: "Unit: Rank"
  trigger_condition_description_rank: "Triggers based on the rank of a certain unit."
  trigger_condition_readable_rank: "Does {0} have {1} {2} of {3} at {4} with {5} rank {6}?"
  
  trigger_condition_name_on_load: "When: During Loading"
  trigger_condition_description_on_load: "Triggers at the start of a reload back into the game."
  trigger_condition_readable_on_load: "Do you load back into the game?"
...