---

triggerActions:
  - id: modify_experience
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      - type: operation
      - type: integer
  - id: modify_rank
    parameters:
      - type: unit_class_star
      - type: location_star
      - type: player_neutral_star
      - type: operation
      - type: integer
  - id: update_leveling
    hidden: true
  
...